version: '3'
services:

  api:
    build:
      context: ./api
    image: ops-repository:local
    working_dir: /var/www/html/
    ports:
      - "80:80"
    environment:
      APP_ENV: dev
      APP_SECRET: 4ac19caa63d28c7a8a7da502a4629201
      DATABASE_URL: "postgresql://ops:pass@postgres:5432/ops?serverVersion=13&charset=utf8"
      XDEBUG_MODE: coverage
      BASE: /
    volumes:
      - ./api:/var/www/html/
      - ./cfg/apache:/etc/apache2/sites-enabled
    depends_on:
      - postgres

  db-update:
    image: ops-repository:local
    user: "1000:1000"
    environment:
      APP_ENV: dev
      DATABASE_URL: "postgresql://ops:pass@postgres:5432/ops?serverVersion=13&charset=utf8"
    volumes:
      - ./api:/var/www/html/
    command: php bin/console doctrine:schema:update --force

  ui:
    image: node:16.17.1-slim
    working_dir: /home/node/app
    environment:
      PORT: 3000
      REACT_APP_API_URL: http://localhost/api
    ports:
      - "3000:3000"
    command: npm start
    volumes:
      - ./ui:/home/node/app
      - ui_node_modules:/home/node/app/node_modules

  postgres:
    image: postgres:13-alpine3.16
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: ops

  adminer:
    image: adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  grafana:
    image: grafana/grafana:7.5.6
    user: "472"
    ports:
      - 3001:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3001
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  prometheus:
    image: prom/prometheus:v2.17.2
    ports:
      - "9090:9090"
    volumes:
      - ./cfg/prometheus:/etc/prometheus
    command:
      - --web.enable-lifecycle
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=180d
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles

volumes:
  ui_node_modules: